require 'sinatra'
require 'tagz'
require 'zipruby'
require 'wilson/web'

include Tagz.globally

Sinatra::Application.set(:run => false, :environment => 
:development)


require 'addressable/template'

module URITemplates
  def t(arg)
    Addressable::Template.new(arg)
  end
  
  module RouteGeneration
    def g(method, variables)
      variable_keys = variables.keys
      route = self.class.routes[method].find do |a|
                a[1].all? {|k| variable_keys.include? k}
              end

      template = route[0]
      template.expand(variables).tap do |uri|
        template.keys.each do |k|
          variables.delete k
        end
        uri.query_values = variables
      end
    end
  end
end

#
# The TSSApp class serves log files generated by the Tsung stress
# testing tool.
#
# @representation xml
#     <?xml encoding="utf-8">
#     <report>
#       bla
#     </report>
# @representation json
#     { "report": "bla" }
#
class TSSApp < Sinatra::Application
  include Wilson::Web
  extend URITemplates
  include URITemplates::RouteGeneration
  
  configure do
    set :public, COMMAND_LINE.logdir
    set :logdir, COMMAND_LINE.logdir
    set :tsung_stats, COMMAND_LINE.tsung_stats
  end
  
  ##
  # Shows the list of all logs present on the machine.
  #
  # @output_types [text/html]
  # @output_languages [en-US]
  #
  get t'/' do
    logdirs = (Dir.entries(options.logdir) - [".", ".."]).sort
    logdirs.reject! {|file| file =~ /\.zip/ }
    logdirs.reject! {|file| file =~ /tsung/ }
    list_dirs(logdirs)  
  end
  
  ##
  # Shows a report. If the report is not generated already, it will be.
  #
  # @url_param dir The date on which the measurement was taken.
  # @get force If present and set to any value, 
  #              regeneration of the report is forced
  # @output_types [text/html]
  # @output_languages [en-US]
  #
  get t'/{dir}/report.html' do
    run_stats(params[:dir])
  end
  
  #
  # Delivers a report as zip file. If not generated, report generation takes place.
  #
  # @url_param [dir] The date on which the measurement was taken.
  #
  # @output_types [application/zip]
  #
  get t'/{dir}.zip' do
    filename = params[:dir].gsub(/:/, '-')
    unless File.exists?(File.join(options.logdir, "#{filename}.zip"))
      zip(params[:dir], filename)
    end
    attachment("#{filename}.zip")
    content_type("application/zip")
    File.read(File.join(options.logdir, "#{filename}.zip"))
  end
  
  #
  # Runs the report generation. If a report already exists, 
  # it wont be generated a second time, unless forced explicitly.
  #
  # @param dir [String] The logfile directory of the report.
  # @param force [true, false] If set to true, the report gets
  #                            created unconditionally.
  #
  # @return [String] The contents of #{dir}/report.html
  def run_stats(dir, force = false)
    Dir.chdir( File.join(options.logdir, dir) ) do
      unless File.exists?('report.html') && force == false
        system(options.tsung_stats)
      end
      File.read('report.html')
    end
  end
  
  #
  # Creates a zip file out of a directory. 
  #
  # @param dir [String] The directories name.
  # @param filename [String] The output filename.
  #
  # @return [undefined] unspecified
  def zip(dir, filename)
    Dir.chdir( File.join(options.logdir) ) do
      unless File.exists?("#{filename}.zip")
        Zip::Archive.open("#{filename}.zip", Zip::CREATE) do |ar|
          Dir.glob("#{dir}/**/*").each do |path|
            if File.directory?(path)
              ar.add_dir(path)
            else
              ar.add_file(path, path)
            end
          end
        end
      end
    end
  end
  
  #
  # Generates a HTML document listing of all logs present on the machine.
  #
  # @param logdirs [Array<String>] The directories that contain logs.
  #
  # @return [String<text/html>] The generated document.
  def list_dirs(logdirs)
    
    html_ do
      
      head_ do
        title_ "Logpickin'"
      end
    
      body_ do
        h1_ "Pick a log:"
        
        ul_(:class => 'logs') do
          logdirs.each do |dir|
            li_(:class => 'log') do
              a_ "Log #{dir}", :href => "/#{dir}/report.html"
              a_ "As zip", :href => "/#{dir}.zip"
            end
          end
        end
      end
    end
      
  end
end